# Configuración privada de la base de datos local
spring.datasource.url=jdbc:mysql://localhost:3306/DBProyect
spring.datasource.username=root
spring.datasource.password=MiClaveSegura123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
